ACTIVATION_METHOD_TYPES_REGULAR = "regular"
ACTIVATION_METHOD_TYPES_ALTERNATIVE = "alternative"

ACTIVATION_RESULT_ACTION_CHDIR = "change_dir"
ACTIVATION_RESULT_ACTION_OPEN_DIR_IN_TAB = "open_dir_in_tab"
ACTIVATION_RESULT_ACTION_MESSAGE = "message"
