name: C/C++ CI on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set vcpkg's response file path used as part of cache's key.
        uses: lukka/set-shell-env@master
        with:
          VCPKGRESPONSEFILE: ${{ github.workspace }}/TabsPls_Qt/cmakeliststxt/vcpkg_x64-windows.txt
          VCINSTALLDIR: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC"

      - name: provision embeddable python
        run: 'python "${{ github.workspace }}/TabsPls_Qt/LightSpeedFileExplorer/provision_embeddable_python.py" --platform x64-Windows --outdir "${{ github.workspace }}/../../_temp"'
        shell: bash
      - name: dir
        run: find "$VCINSTALLDIR"
        shell: bash

      - name: provision vcruntime libraries 
        run: '"${{ github.workspace }}/TabsPls_Qt/LightSpeedFileExplorer/provision_embeddable_vcruntime.sh" "${{ github.workspace }}/../../_temp/tabspls_embedded_vcruntime"'
        shell: bash

      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash
      - name: Restore artifacts, or run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@v7
        id: runvcpkg
        with:
          vcpkgArguments: '@${{ env.VCPKGRESPONSEFILE }}'
          vcpkgDirectory: '${{ github.workspace }}/TabsPls_Qt/vcpkg'
          # Ensure the cache key changes any time the content of the response file changes.
          appendedCacheKey: ${{ hashFiles( env.VCPKGRESPONSEFILE ) }}

      - name: Run CMake with MSBuild
        uses: lukka/run-cmake@v2
        id: runcmake
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/TabsPls_Qt/LightSpeedFileExplorer/CMakeLists.txt'
          cmakeGenerator: VS16Win64
          cmakeAppendedArgs: -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/../../_temp/deploy"
          buildWithCMakeArgs: --target install --config Release
          useVcpkgToolchainFile: true
      - name: Prints output of run-vcpkg's task
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_TRIPLET_OUT }}' "

      - name: dir
        run: find "${{ github.workspace }}/../../_temp"
        shell: bash
