name: C/C++ CI on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    env:
      tabspls_build_dir: '"${{ github.workspace }}/TabsPls_Qt/LightSpeedFileExplorer/build"'

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: create build folder
        shell: bash
        run: 'mkdir ${{ env.tabspls_build_dir }}'

      - name: provision embeddable python
        run: 'python "${{ github.workspace }}/TabsPls_Qt/LightSpeedFileExplorer/provision_embeddable_python.py" --platform x64-Windows --outdir ${{ env.tabspls_build_dir }}'
        shell: bash

      - name: provision vcruntime libraries 
        run: '"${{ github.workspace }}/TabsPls_Qt/LightSpeedFileExplorer/provision_embeddable_vcruntime.sh" ${{ env.tabspls_build_dir }}/tabspls_embedded_vcruntime'
        shell: bash

      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash
      - name: Restore artifacts, or run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ github.workspace }}/TabsPls_Qt/vcpkg'
          runVcpkgInstall: true

      - name: Run CMake with MSBuild
        uses: lukka/run-cmake@v2
        id: runcmake
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/TabsPls_Qt/LightSpeedFileExplorer/CMakeLists.txt'
          cmakeGenerator: VS16Win64
          cmakeAppendedArgs: -DTABSPLS_PYTHON_WILL_BE_PACKAGED=ON -DCPACK_BINARY_ZIP=ON -DCPACK_BINARY_NSIS=OFF -DTABSPLS_PORTABLE_WINDOWS=ON
          buildDirectory: '${{ github.workspace }}/TabsPls_Qt/LightSpeedFileExplorer/build'
          buildWithCMakeArgs: --target package --config Release
          useVcpkgToolchainFile: true
      - name: Prints output of run-vcpkg's task
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_TRIPLET_OUT }}' "

      - name: dir
        run: 'find ${{ env.tabspls_build_dir }}'
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: LightSpeedFileExplorer-portable
          path: TabsPls_Qt/LightSpeedFileExplorer/build/LightSpeedFileExplorer*.zip

