name: C/C++ Core Test ran on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set vcpkg's response file path used as part of cache's key.
        uses: lukka/set-shell-env@master
        with:
          VCPKGRESPONSEFILE: ${{ github.workspace }}/TabsPls_Test/cmakeliststxt/vcpkg_x64-windows.txt
      - name: pip dependencies
        run: pip install virtualenv

      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash
      - name: Restore artifacts, or run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@v7
        id: runvcpkg
        with:
          vcpkgArguments: '@${{ env.VCPKGRESPONSEFILE }}'
          vcpkgDirectory: '${{ github.workspace }}/TabsPls_Test/vcpkg'
          # Ensure the cache key changes any time the content of the response file changes.
          appendedCacheKey: ${{ hashFiles( env.VCPKGRESPONSEFILE ) }}

      - name: Run CMake with MSBuild
        uses: lukka/run-cmake@v2
        id: runcmake
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtBasic
          cmakeListsTxtPath: '${{ github.workspace }}/TabsPls_Test/CMakeLists.txt'
          cmakeGenerator: VS16Win64
          cmakeBuildType: Release
          useVcpkgToolchainFile: true
      - name: Prints output of run-vcpkg's task
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_TRIPLET_OUT }}' "

      - name: dir
        run: find "${{ github.workspace }}/../../_temp"
        shell: bash
      - name: Run CTest
        run: |
          cd "${{ github.workspace }}/../../_temp"
          ctest -C Release --rerun-failed --output-on-failure
